<?php

/**
 * @file
 * Hook implementations for Wizzlern Example News module.
 */

/**
 * Implements hook_cron().
 */
function we_news_cron() {

  // Get news articles that are not yet archived after 1 year.
  $threshold = strtotime('-1 year', $_SERVER['REQUEST_TIME']);
  $query = \Drupal::entityTypeManager()->getStorage('node')->getQuery()
    ->condition('type', 'news')
    ->condition('field_news_archive', 0)
    ->condition('created', $threshold, '<');
  $nids = $query->execute();

  // Mark news articles as archived.
  foreach ($nids as $nid) {
    /** @var \Drupal\node\Entity\Node $node */
    $node = \Drupal::entityTypeManager()->getStorage('node')->load($nid);
    $node->set('field_news_archive', 1);
    $node->save();
  }
}
