module:
  admin_toolbar: 0
  block: 0
  breakpoint: 0
  comment: 0
  config: 0
  contextual: 0
  datetime: 0
  default_content: 0
  hal: 0
  rest: 0
  serialization: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  extra_field: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  user: 0
  views: 0
  views_ui: 0
  we_content: 0
  we_news: 0
  menu_link_content: 1
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
